services:
  - type: web
    name: agrisage
    env: python
    buildCommand: pip install -r backend/requirements.txt && npm install --prefix frontend && npm run build --prefix frontend
    startCommand: gunicorn --chdir backend app:app
